/**
 * Style reminder — Om’s Field Station: this is a private composition desk, not a generic CMS.
 * The local preview gate is intentionally labelled non-secure; only real server auth may become an admin boundary.
 */
import { CheckCircle2, ChevronDown, Eye, KeyRound, LockKeyhole, Palette, PencilLine, Plus, Save, ShieldAlert, Sparkles, StickyNote, Type, WandSparkles } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import { Link } from "wouter";
import { FONT_CATALOG, PALETTES, STICKER_MOTIFS, SYMBOLS, VECTOR_MARKS } from "@/data/editorCatalog";
import { DEFAULT_PRESENTATION, type RecordPresentation, saveLocalRecord } from "@/lib/localArchive";
import { PageFooter, ReadingRail } from "@/components/SiteChrome";

type FormState = { title: string; category: string; evidenceMode: string; excerpt: string; body: string; question: string; presentation: RecordPresentation };
const EMPTY_FORM: FormState = { title: "", category: "Weathered Stone", evidenceMode: "Material record", excerpt: "", body: "", question: "", presentation: DEFAULT_PRESENTATION };

const CATEGORIES = ["Weathered Stone", "Celestial Geometry", "Ritual Technology", "Folklore Afterlife", "Metamorph Myth", "Guardian Theophany", "Visitor Figures", "Border Creature", "Redacted Method"];
const EVIDENCE_MODES = ["Material record", "Ritual context", "Cultural myth", "Modern speculation", "Fictional echo"];

export default function ArchiveRoom() {
  const [unlocked, setUnlocked] = useState(false);
  const [passphrase, setPassphrase] = useState("");
  const [accessError, setAccessError] = useState("");
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [saved, setSaved] = useState(false);
  const selectedFont = useMemo(() => FONT_CATALOG.find((font) => font.id === form.presentation.fontId) || FONT_CATALOG[0], [form.presentation.fontId]);

  const submitAccess = (event: FormEvent) => {
    event.preventDefault();
    if (passphrase === "Pass@123") { setUnlocked(true); setAccessError(""); } else { setAccessError("This local preview phrase does not match. Check the temporary phrase and try again."); }
  };
  const patchPresentation = (patch: Partial<RecordPresentation>) => setForm((current) => ({ ...current, presentation: { ...current.presentation, ...patch } }));
  const saveRecord = (event: FormEvent) => {
    event.preventDefault();
    if (!form.title || !form.body) return;
    const slug = form.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    saveLocalRecord({ slug, title: form.title, category: form.category, excerpt: form.excerpt || "A new record in Om’s local field notebook.", body: form.body, keyQuestion: form.question || "What will this evidence change?", eyebrow: `${form.evidenceMode.toUpperCase()} · OM’S DESK`, date: "LOCAL DEVICE", readTime: "Draft", presentation: form.presentation });
    setSaved(true); setForm(EMPTY_FORM); window.setTimeout(() => setSaved(false), 3600);
  };
  const previewStyle = { "--studio-font": selectedFont.value, "--studio-palette": form.presentation.paletteHex } as CSSProperties;

  return <main className="archive-room-page"><ReadingRail current="PRIVATE ROOM / OMN" />
    {!unlocked ? <section className="access-page"><div className="access-seal"><img src="/assets/kemet-mark.png" alt="" /></div><div className="access-copy"><span className="micro-label">LOCAL PREVIEW GATE · OM NANDURKAR</span><h1>Only the keeper<br />opens the <em>cabinet.</em></h1><p>This temporary desk gate is for local preview only. It does not protect the site or its data. Real Om-only access will use the project’s authenticated application layer once Supabase is finalized.</p></div><form className="access-form" onSubmit={submitAccess}><label><KeyRound size={16} /><input type="password" value={passphrase} onChange={(event) => setPassphrase(event.target.value)} placeholder="Enter temporary preview phrase" autoComplete="off" /></label>{accessError && <p className="access-error">{accessError}</p>}<button className="ink-button" type="submit" disabled={!passphrase.trim()}>Open the local studio <LockKeyhole size={16} /></button><small><ShieldAlert size={14} /> Local preview only — not secure authentication.</small></form></section> : <section className="studio-page">
      <header className="studio-header"><div><span className="micro-label">OM NANDURKAR / EDITORIAL STUDIO</span><h1>Compose the<br /><em>record.</em></h1><p>Control the words, evidence framing, font, wash, symbols, vector trace, sticker motif, and margin note from one field desk.</p></div><div className="studio-header-actions"><Link href="/archive" className="underlined-link">Public archive</Link><Link href="/investigations" className="underlined-link">Anomaly Index</Link></div></header>
      <div className="studio-warning"><ShieldAlert size={18} /><p><strong>Temporary local mode.</strong> This browser stores drafts on this device. The preview gate is not a security boundary. Authenticated, persistent publishing is the next server-backed phase.</p></div>
      <form className="studio-layout" onSubmit={saveRecord}>
        <section className="studio-canvas"><div className="studio-section-label"><PencilLine size={16} /><span>01 / WRITING LAYER</span></div><div className="studio-title-row"><label><span>Record title</span><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Name the question" required /></label><div className="studio-symbol-current">{form.presentation.symbol}</div></div><div className="studio-meta-grid"><label><span>Classification</span><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label><span>Evidence mode</span><select value={form.evidenceMode} onChange={(event) => setForm({ ...form, evidenceMode: event.target.value })}>{EVIDENCE_MODES.map((mode) => <option key={mode}>{mode}</option>)}</select></label></div><label><span>Guiding question</span><input value={form.question} onChange={(event) => setForm({ ...form, question: event.target.value })} placeholder="What should the reader keep asking?" /></label><label><span>Archive summary</span><textarea value={form.excerpt} onChange={(event) => setForm({ ...form, excerpt: event.target.value })} placeholder="The short record that invites a reader inside." rows={3} /></label><label><span>Field text</span><textarea className="article-draft" value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} placeholder="Begin with the fragment, then let the evidence lead." rows={13} required /></label></section>
        <aside className="studio-controls"><div className="studio-section-label"><WandSparkles size={16} /><span>02 / PRESENTATION LAYER</span></div><details open><summary><Type size={15} /> Type library <ChevronDown size={15} /></summary><div className="studio-control-body"><label><span>Curated field font · 50 options</span><select value={form.presentation.fontId} onChange={(event) => { const font = FONT_CATALOG.find((item) => item.id === event.target.value) || FONT_CATALOG[0]; patchPresentation({ fontId: font.id, fontFamily: font.value }); }}>{FONT_CATALOG.map((font) => <option value={font.id} key={font.id}>{font.label}</option>)}</select></label><p className="studio-font-sample" style={{ fontFamily: selectedFont.value }}>The question leaves a typeface behind.</p></div></details><details open><summary><Palette size={15} /> Pastel &amp; watercolour wash <ChevronDown size={15} /></summary><div className="studio-palette-grid">{PALETTES.map((palette) => <button type="button" aria-label={palette.label} title={palette.label} key={palette.id} className={form.presentation.palette === palette.id ? "selected" : ""} style={{ background: palette.value }} onClick={() => patchPresentation({ palette: palette.id, paletteHex: palette.value })}><i /></button>)}</div></details><details><summary><Sparkles size={15} /> Script &amp; symbol mark <ChevronDown size={15} /></summary><div className="studio-symbol-grid">{SYMBOLS.map((symbol) => <button type="button" key={symbol.id} className={form.presentation.symbol === symbol.value ? "selected" : ""} onClick={() => patchPresentation({ symbol: symbol.value })}><b>{symbol.value}</b><span>{symbol.label.split(" · ")[1]}</span></button>)}</div></details><details><summary><Eye size={15} /> Vector trace &amp; sticker <ChevronDown size={15} /></summary><div className="studio-control-body"><label><span>Vector trace</span><select value={form.presentation.vector} onChange={(event) => patchPresentation({ vector: event.target.value })}>{VECTOR_MARKS.map((mark) => <option key={mark.id} value={mark.value}>{mark.label}</option>)}</select></label><label><span>Sticker motif</span><select value={form.presentation.motif} onChange={(event) => patchPresentation({ motif: event.target.value })}>{STICKER_MOTIFS.map((motif) => <option key={motif.id} value={motif.value}>{motif.label}</option>)}</select></label></div></details><details open><summary><StickyNote size={15} /> Sticky note data <ChevronDown size={15} /></summary><div className="studio-control-body"><label><span>Note heading</span><input value={form.presentation.stickyTitle} onChange={(event) => patchPresentation({ stickyTitle: event.target.value })} placeholder="Margin note" /></label><label><span>Note text</span><textarea value={form.presentation.stickyBody} onChange={(event) => patchPresentation({ stickyBody: event.target.value })} rows={3} placeholder="Leave an annotation for the reader." /></label></div></details></aside>
        <section className={`studio-preview vector-${form.presentation.vector}`} style={previewStyle}><div className="studio-preview-label"><Eye size={15} /> READER PREVIEW / LOCAL</div><div className={`studio-preview-motif motif-${form.presentation.motif}`}><img src="/assets/om-field-station-stickers.png" alt="" /></div><span className="studio-preview-symbol">{form.presentation.symbol}</span><span className="studio-preview-mode">{form.evidenceMode}</span><h2>{form.title || "Your record title"}</h2><p>{form.excerpt || "A summary will become the reader’s first clue."}</p><div className="studio-preview-sticky"><span>{form.presentation.stickyTitle || "Margin note"}</span><strong>{form.presentation.stickyBody || "Leave an annotation for the reader."}</strong></div><small>{form.category} · OMN / LOCAL DEVICE</small></section>
        <footer className="studio-save-row"><span>{saved ? <><CheckCircle2 size={17} /> Saved locally with its full presentation layer.</> : <><Plus size={17} /> One local record can later become one database row.</>}</span><button className="ink-button" type="submit"><Save size={16} /> Save local draft</button></footer>
      </form>
    </section>}<PageFooter /></main>;
}
