import { BookOpen, ChevronLeft, Eye, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useCuratorAuth } from "@/hooks/useCuratorAuth";

const handbookSections = [
  { number: "01", title: "Identify", body: "Name the question, give it a reader URL, choose its status, and add place or period only when they help orientation." },
  { number: "02", title: "Write", body: "Draft the summary and body first. A design choice cannot repair an unclear question. Keep Om’s take separate from the documented record." },
  { number: "03", title: "Evidence", body: "Keep claim, record, counterargument, anomaly, and interpretation distinct. Add real source paths, public Drive evidence, and map coordinates only when each can be responsibly identified." },
  { number: "04", title: "Shape & release", body: "Preview the reader paper, use visual marks sparingly, then review the evidence prompts before saving a draft or publishing." },
];

export default function OmGuide() {
  const { loading, isAuthenticated } = useCuratorAuth();
  if (loading) return <main className="admin-loading">Opening Om’s desk guide…</main>;
  if (!isAuthenticated) return <main className="admin-gate"><ShieldCheck size={34} /><span className="micro-label">OM-ONLY DESK GUIDE</span><h1>This field guide belongs<br />to <em>Om.</em></h1><p>Unseal the curator puzzle to open the authoring handbook.</p><Link href="/om-dashboard">Return to curator entry</Link></main>;
  return <main className="om-guide-page"><Link className="om-guide-back" href="/om-dashboard?desk=cases"><ChevronLeft size={16} /> Back to case files</Link><section className="om-guide-hero"><span className="micro-label">OM’S PRIVATE FIELD GUIDE · COMPLETE DESK HANDBOOK</span><h1>Make one <em>clear</em><br />case at a time.</h1><p>This is the in-app operational handbook for the four-pass desk. It preserves the essential workflow, release, preview, evidence, asset, map, letter, and maintenance guidance alongside the editor.</p></section><section className="om-guide-grid">{handbookSections.map((section) => <article key={section.number}><span>{section.number}</span><h2>{section.title}</h2><p>{section.body}</p></article>)}</section><section className="om-guide-checklist"><BookOpen size={22} /><div><span className="micro-label">BEFORE PUBLISHING</span><h2>One final evidence pass.</h2><ul><li>The title, URL, summary, and long-form body are complete.</li><li>The claim is visibly distinct from documented material and interpretation.</li><li>A counterargument or uncertainty is present when the topic needs one.</li><li>Every source card gives readers a real path to inspect.</li></ul></div></section><section className="om-guide-protocols"><article><Eye size={19} /><span className="micro-label">PRIVATE READER PREVIEW</span><h2>Preview the current desk draft.</h2><p>Use <strong>Open reader preview</strong> only from the case desk after entering a composition. It opens the current, unsaved draft in a private browser tab. It cannot publish, create a public link, or replace a saved case file.</p></article><article><span className="micro-label">ASSETS, MAPS & LETTERS</span><h2>Keep the record accountable.</h2><p>Drive images must be public to anyone with the link. Map pins require a responsibly identified latitude and longitude. Reader letters are prompts, not content: <strong>Start a draft</strong> copies the prompt into a new unpublished workspace for Om to rewrite and evidence.</p></article><article><span className="micro-label">MAINTENANCE PROTOCOL</span><h2>Update the handbook with the desk.</h2><p>After a substantial product or workflow change, update the dated maintenance log and affected instructions in the project handbook. Planned release remains coming soon; save a draft or publish now until a separate scheduling workflow exists.</p></article></section></main>;
}
