import { AnnotatedText } from "@/components/NotebookAnnotations";
import { ArrowUpRight, Link2, Orbit } from "lucide-react";
import { useState } from "react";
import "./caseEvidenceContext.css";

type CaseEvidenceBoardProps = { claim?: string | null; documentedEvidence?: string | null; counterargument?: string | null; anomaly?: string | null; theory?: string | null; sources?: Array<{ id: number; label: string; url: string }>; relatedCases?: Array<{ id: number; title: string; caseNumber: string | null }> };
export const evidenceText = (value?: string | null) => value?.trim() ? value.trim() : "Awaiting Om’s field note.";
type EvidenceRecord = { id: string; label: string; value: string; className: string };

export function CaseEvidenceBoard({ claim, documentedEvidence, counterargument, anomaly, theory, sources = [], relatedCases = [] }: CaseEvidenceBoardProps) {
  const [selected, setSelected] = useState<string | null>(null);
  const records: EvidenceRecord[] = [{ id: "claim", label: "THE CLAIM", value: evidenceText(claim), className: "card-claim" }, { id: "record", label: "THE RECORD", value: evidenceText(documentedEvidence), className: "card-record" }, { id: "anomaly", label: "THE ANOMALY", value: evidenceText(anomaly), className: "card-anomaly" }, { id: "counter", label: "COUNTERARGUMENT", value: evidenceText(counterargument), className: "card-counter" }, { id: "theory", label: "INTERPRETATION", value: evidenceText(theory), className: "card-theory" }];
  const active = records.find((record) => record.id === selected);
  return <section className="case-evidence-board"><header><span className="micro-label">EVIDENCE BOARD / OMN METHOD</span><h2>Follow the<br /><em>thread.</em></h2><p>Connections are prompts for examination, not proof of causation. Select a fragment to inspect its field note.</p>{(sources.length > 0 || relatedCases.length > 0) && <div className="case-board-context"><span><Link2 size={13} /> {sources.length ? `${sources.length} source ${sources.length === 1 ? "thread" : "threads"}` : "No source thread filed"}</span>{sources.slice(0, 2).map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.id}>{source.label}<ArrowUpRight size={11} /></a>)}{relatedCases.length > 0 && <span><Orbit size={13} /> {relatedCases.length} related {relatedCases.length === 1 ? "case" : "cases"}</span>}</div>}</header><div className="case-board-network" aria-label="Case evidence relationship board"><svg viewBox="0 0 1100 480" aria-hidden="true"><path d="M155 90 C330 180, 380 190, 520 230 S750 300, 930 370" /><path d="M155 90 C290 90, 385 345, 520 230" /><path d="M520 230 C680 155, 820 135, 930 370" /></svg>{records.map((record) => <button type="button" aria-pressed={selected === record.id} onClick={() => setSelected(selected === record.id ? null : record.id)} className={`case-board-card ${record.className} ${selected === record.id ? "is-inspected" : ""}`} key={record.id}><span>{record.label}</span><p><AnnotatedText value={record.value} /></p><i>INSPECT ↗</i></button>)}<i className="case-board-pin pin-one" /><i className="case-board-pin pin-two" /><i className="case-board-pin pin-three" /></div>{active && <aside className="case-evidence-inspector" aria-live="polite"><div><span className="micro-label">FIELD NOTE / {active.label}</span><h3>Hold this<br /><em>fragment.</em></h3></div><p><AnnotatedText value={active.value} /></p><button type="button" onClick={() => setSelected(null)}>Return to board ×</button></aside>}</section>;
}
