import { Command, KeyRound, LockKeyhole, RotateCcw, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";
import { CURATOR_RELICS, type CuratorRelicId } from "@shared/curatorPuzzles";

export function CuratorPuzzleGate({ onUnlocked }: { onUnlocked: () => void }) {
  const { data: puzzle, isLoading: puzzleLoading } = trpc.curator.puzzle.useQuery();
  const [sequence, setSequence] = useState<CuratorRelicId[]>([]);
  const [showOverride, setShowOverride] = useState(false);
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("");
  const solve = trpc.curator.solve.useMutation({ onSuccess: (result) => { if (result.authenticated) onUnlocked(); else { setNotice("The mechanism resists. Reconsider the order."); setSequence([]); } }, onError: () => setNotice("The chamber could not verify the sequence. Try again."), });
  const unlock = trpc.curator.unlock.useMutation({ onSuccess: (result) => { if (result.authenticated) onUnlocked(); else setNotice("That password did not wake the mechanism."); }, onError: () => setNotice("The chamber could not verify the password."), });
  useEffect(() => { const openOverride = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setShowOverride(true); } }; window.addEventListener("keydown", openOverride); return () => window.removeEventListener("keydown", openOverride); }, []);
  useEffect(() => { setSequence([]); setNotice(""); }, [puzzle?.id]);
  const activeRelics = puzzle?.relicIds.map((id) => CURATOR_RELICS.find((relic) => relic.id === id)).filter((relic): relic is typeof CURATOR_RELICS[number] => Boolean(relic)) || [];
  const select = (id: CuratorRelicId) => { if (!puzzle || solve.isPending || sequence.includes(id)) return; const next = [...sequence, id]; setSequence(next); setNotice(""); if (next.length === activeRelics.length) solve.mutate({ puzzleId: puzzle.id, sequence: next }); };
  const busy = solve.isPending || unlock.isPending;
  if (puzzleLoading || !puzzle) return <main className="admin-loading"><Sparkles className="spin" /> Reading the antechamber tablet…</main>;
  return <main className="puzzle-gate"><div className="puzzle-gate-noise" /><section className="puzzle-gate-table"><div className="puzzle-gate-heading"><span className="micro-label">THEOREM OF KEMET · {puzzle.name.toUpperCase()}</span><h1>{puzzle.title}</h1><p>{puzzle.instruction}</p>{puzzle.clue && <small className="puzzle-clue">Field clue · {puzzle.clue}</small>}</div><div className="puzzle-sequence" aria-label="Selected relic sequence">{Array.from({ length: activeRelics.length }, (_, index) => <span key={index}>{sequence[index] ? CURATOR_RELICS.find((relic) => relic.id === sequence[index])?.glyph : "·"}</span>)}</div><div className="puzzle-relic-grid">{activeRelics.map((relic) => <button type="button" key={relic.id} disabled={busy || sequence.includes(relic.id)} onClick={() => select(relic.id)}><i>{relic.glyph}</i><span>{relic.label}</span></button>)}</div><div className="puzzle-gate-footer"><button type="button" onClick={() => { setSequence([]); setNotice(""); }} disabled={busy}><RotateCcw size={15} /> Reset tablet</button><button type="button" onClick={() => setShowOverride(true)}><Command size={15} /> ⌘ / Ctrl + K</button></div>{notice && <p className="puzzle-notice" aria-live="polite">{notice}</p>}<aside><Sparkles size={16} /><span>The relic order is checked on the server. The password is never stored in this browser.</span></aside></section>{showOverride && <div className="puzzle-override" role="dialog" aria-modal="true" aria-label="Curator password override"><form onSubmit={(event) => { event.preventDefault(); unlock.mutate({ password }); }}><button type="button" className="puzzle-dismiss" onClick={() => setShowOverride(false)}>×</button><LockKeyhole size={23} /><span className="micro-label">KEEPER OVERRIDE</span><h2>Use the old<br /><em>spoken key.</em></h2><p>Pressing the shortcut never reveals the key—it only opens this private input.</p><label>Password<input autoFocus type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter curator password" autoComplete="current-password" /></label><button className="ink-button" type="submit" disabled={!password || busy}><KeyRound size={16} /> Unseal desk</button></form></div>}</main>;
}
